# Generated by Django 6.0.5 on 2026-05-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_owner_message_delete_breeder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
