# Generated by Django 6.0.5 on 2026-05-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='fur_length',
        ),
    ]
