# Generated by Django 6.0.5 on 2026-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_remove_cat_fur_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='fur_length',
            field=models.CharField(choices=[('short', 'Короткая'), ('long', 'Длинная'), ('hairless', 'Без шерсти')], default='short', max_length=10),
        ),
    ]
