# Generated by Django 6.0.5 on 2026-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_cat_fur_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='fur_length',
            field=models.CharField(choices=[('short', 'Короткая'), ('long', 'Длинная'), ('hairless', 'Лысая')], default='short', max_length=10),
        ),
    ]
